Added commands for FunixBot
FunixProductions/FunixBot pull request #22
Opened 2023-03-08 13:23 UTC by iGameCreep

- Added command files
- Edited slashCommandInteraction event to make it listen to Slash Commands

2023-03-08 15:37 UTC, iGameCreep commented
Tu peux faire des tests avec ce code, je ne suis pas sur qu'il fonctionne à 100% étant donné que j'ai du modifier 2-3 trucs sur les imports / packages

2023-03-09 17:15 UTC, iGameCreep commented
Hello, j'ai update mon code pour le faire fonctionner avec l'interface SlashCommand au lieu de la classe BotCommand et de l'interface onUserCommand.
J'ai aussi update mes imports et noms de package car a chaque fois soit je laissais fr.gamecreep soit j'oubliais le .discord et je mettais juste fr.funixgaming.funixbot
Bien sur, prends ton temps bg !

2023-03-11 18:48 UTC, iGameCreep commented
Hello, petite update : ajout des commandes à prefix !
Bien sur, testé en local avec mon bot, c'est fonctionnel de mon coté !

2023-03-11 20:26 UTC, iGameCreep commented
Comme demandé, suppression des commandes a prefix !

2023-03-13 14:41 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/FunixBot.java
> +            CommandList cmdList;
Ici tu pourrais directement initialiser ta classe commande liste comme ceci :
```java
CommandList cmdList = new CommandList();
```
ça améliore la lecture du code.

Tu devrais aussi créer une méthode dans cette même classe que tu appelleras dans le constructeur de FunixBot. Toujours dans une démarche de lecture de code ! C'est important, pour l'instant c'est pas très important car le bot n'as pas beaucoup de volume de code mais quand tu arrive sur un projet avec beaucoup de volume de code c'est délicat.

Pense aussi à faire de commentaires sur tes methodes et variables :D si tu peux c'est pas obligatoire mais ça serait royal !

2023-03-13 14:43 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/commands/CommandGnou.java
> +public class CommandGnou implements SlashCommand {
Très bien rien à dire, pour les getter et setter (getName et getDescription) utilise la librairie loombok, qui génère automatiquement des getter et setter en fonction des variables déclarées dans ta classe

Plus d'infos : https://www.youtube.com/watch?v=z7bsNF2Dtf0

2023-03-13 14:46 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/commands/utils/CommandList.java
> +public class CommandList {
En réalité je suis pas sûr de l'utilité de cette classe.
Tu encapsule une liste dans une classe ce qui est overkill dans ce cas d'usage. Tu devrais juste déclarer la liste dans la classe funixbot je pense.
A voir parce que j'imagine que utilise cette classe pour la commande help.

Il faudrait créer un bean pour cette classe du coup mais là on arrive dans des notions bien trop avancées pour l'instant donc je valide la classe je verrais si je la changerais ou non !

2023-03-13 14:48 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/configs/JdaEventsConfig.java
> +    public BotButtonEvents botButtonEvents(FunixBot funixBot,
J'imagine que tu as du lire ce que j'avais fait au dessus et en vrai tu as bien implémenté ton bean GG, ce fonctionnement là du coup vient pas de java directement c'est lié au framework que j'utilise qui s'apelle spring boot. C'est très vase comme framework je t'expliquerais peut-être un jour si tu continues dans la voie du java

2023-03-13 14:48 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/events/BotButtonEvents
> +public class test extends ListenerAdapter {
Je vais avoir besoin de commentaires sur les methodes et classes ici pour mieux comprendre le code, surtout si tu utilise des streams.

2023-03-13 14:50 UTC, FunixG reviewed
Dans l'ensemble c'est très positif ! Essaye de voir les retours que je t'ai fait pour rendre la PR parfaite puis on mergera ton code très certainement t'as compris la logique et t'as step up super vite !

2023-03-13 16:29 UTC, iGameCreep commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/commands/utils/CommandList.java
> +public class CommandList {
Hello ! Pour cette classe, je l'ai mis a part car je dois, pour chaque commande, l'ajouter à la liste ( `commandList.add(new HelpCommand())` par exemple ). Ca peut être inclus dans la classe funixbot directement mais ca prendra un peu plus de place. 
A voir si on garde cette classe et qu'on la définis dans le funixbot ou si on la déplace directement dedans

2023-03-13 16:31 UTC, iGameCreep commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/events/BotButtonEvents
> +public class test extends ListenerAdapter {
Hello ! Honnêtement, je ne me souvenais même plus de l'avoir implantée dans ce code... 😅 Je vais le modifier et le commenter, il n'est effectivement pas très clair

2023-03-13 17:33 UTC, iGameCreep commented
Update de la commandList ( avec modification de fonctions )
Utilisation de Getters de lombok

2023-03-13 18:42 UTC, iGameCreep commented
Petit fix + ajout du rolereact !
Je te laisse checker si ça te convient fait comme ça !

2023-03-14 13:39 UTC, FunixG approved these changes

2023-03-14 14:11 UTC, FunixG requested changes
Il y a encore la classe BotButtonEvents à retravailler sinon tu avances bien !

2023-03-16 14:39 UTC, FunixG commented
@iGameCreep Pense a pull master pour mettre à jour ta branche, à commenter le code que je t'ai demandé de commenter et vérifier que le runner github ci fonctionne :D

Je ne peux pas merger en l'état

2023-03-16 16:30 UTC, FunixG requested changes

2023-03-16 16:32 UTC, FunixG commented on funixbot-discord/src/main/java/fr/funixgaming/funixbot/discord/events/BotButtonEvents
> +public class test extends ListenerAdapter {
Ne pas oublier de commenter ce code

2023-03-16 16:49 UTC, FunixG approved these changes

2023-03-16 16:51 UTC, merged